### ISSUE TITLE
Sample Code Runs Wrong

### ISSUE THREAD

**Issue by sotex** [tatarize/potrace#16]
I'm using the sample code and it gives me an error when I run it.

https://github.com/tatarize/potrace/blob/769eadc85ab2ae6c3334686eaab0296fdfdf6abc/README.md?plain=1#L45C1-L85C4

```bash
python potrace.py /d/Pictures/gf2.bmp 
Traceback (most recent call last):
  File "D:\Documets\repos\potrace_raster2vector\potrace.py", line 3, in <module>
    from potrace import Bitmap, POTRACE_TURNPOLICY_MINORITY  # `potracer` library
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Documets\repos\potrace_raster2vector\potrace.py", line 3, in <module>
    from potrace import Bitmap, POTRACE_TURNPOLICY_MINORITY  # `potracer` library
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'Bitmap' from partially initialized module 'potrace' (most likely due to a circular import) (D:\Documets\repos\potrace_raster2vector\potrace.py)
```
I installed the dependency package
```bash
Installing collected packages: potracer
Successfully installed potracer-0.0.4
```

**Comment by Zetsu4i** [comment]
**Rename your file** your confusing the interpreter **dont name your script exactly the same as the name of a package you importing**.

This is a skill issue so you should have asked this in forum instead

You should really spend more time learning python basics before you throw urself into the bigger Bush
